services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /usr/local/apache/domlogs/aditya.printsflick.com.log:/usr/local/apache/domlogs/aditya.printsflick.com.log
    environment:
      - PORT=5000
